### ISSUE TITLE
Error when downloading a configuration

### ISSUE THREAD

**Issue by ghost** [Pistos/diakonos#66]
This was the result from the commandline:

At least one configuration file must exist.
Would you like to download one right now from the Diakonos repository? (y/n)y

^^^^ here I typed y

Fetching configuration from v0.9.5...
RuntimeError: redirection forbidden: http://github.com/Pistos/diakonos/tree/v0.9.5/diakonos.conf?raw=true -> https://github.com/Pistos/diakonos/tree/v0.9.5/diakonos.conf?raw=true
        from /Programs/Ruby/2.2.3/lib/ruby/2.2.0/open-uri.rb:224:in `open_loop'
        from /Programs/Ruby/2.2.3/lib/ruby/2.2.0/open-uri.rb:150:in`open_uri'
        from /Programs/Ruby/2.2.3/lib/ruby/2.2.0/open-uri.rb:716:in `open'
        from /Programs/Ruby/2.2.3/lib/ruby/2.2.0/open-uri.rb:34:in`open'
        from /Programs/Ruby/2.2.3/lib/ruby/site_ruby/2.2.0/diakonos/config.rb:22:in `fetch_conf'
        from /Programs/Ruby/2.2.3/lib/ruby/site_ruby/2.2.0/diakonos/config.rb:70:in`load_configuration'
        from /Programs/Ruby/2.2.3/lib/ruby/site_ruby/2.2.0/diakonos.rb:183:in `initialize'
        from (irb):6:in`new'
        from (irb):6
        from /System/Executables/irb:15:in `<main>'

PS: It would be nice if a minimal configuration could be auto-generated perhaps.

**Comment by shevegen** [comment]
Hello,

Just tried the latest diakonos again or actually "Latest: 0.9.4 (January 8, 2015)" this one.

The redirection problem - could it be resolved by a second-site provided configuration file perhaps, for the time being if it is non-trivial? Or do you happen to have your personal config available somewhere? I could probably then just use your config :) 

Thanks!

**Comment by Pistos** [comment]
It's true that the Internet download of the config should be fixed.  However, the reason you're the first person to mention this is that, really, all the usual vectors of delivering Diakonos as a package to a Linux system should come with at least one configuration file in it, so it's quite odd that one isn't found by the time you run the executable.

How did you obtain Diakonos?  What Linux distro are you using?

You can use this config file as a basis for your own config:

https://raw.githubusercontent.com/Pistos/diakonos/master/diakonos.conf

**Comment by Pistos** [comment]
Closing due to age.

**Comment by xtronics** [comment]
On page https://github.com/Pistos/diakonos

it refers to https://github.com/Pistos/diakonos

Which appears down?  or gone?

The installation instructions are still current?

(Can't run e3 on arm core.. )
,.,.


Still missing the Debian package.

Really best feature - setting the background color different for 
different servers helps prevent running commands in the wrong place.

Thanks for sharing your code..
-- 
--------------------------------------------------------------------------------
Karl Schmidt                                  EMail karl@lrak.net
3209 West 9th Street                             Ph (785) 979-8397
Lawrence, KS 66049

Borrow money from pessimists - they don't expect it back.
--------------------------------------------------------------------------------

**Comment by Pistos** [comment]
@xtronics diakonos.pist0s.ca has been taken down.
